"""Models for OpenGov API."""

from .base import (
    JSONAPIResponse,
    Links,
    Meta,
    Relationship,
    RelationshipData,
    ResourceObject,
)
from .enums import RecordStatus, StepKind, WorkflowStepStatus
from .params import (
    BaseListParams,
    DateRangeFilter,
    ListRecordAdditionalLocationsParams,
    ListRecordAttachmentsParams,
    ListRecordCollectionsParams,
    ListRecordGuestsParams,
    ListRecordsParams,
    ListRecordWorkflowStepCommentsParams,
    ListRecordWorkflowStepsParams,
    PageParams,
)
from .records import (
    AttachmentAttributes,
    AttachmentResource,
    CollectionAttributes,
    CollectionResource,
    GuestAttributes,
    GuestResource,
    LocationAttributes,
    LocationResource,
    RecordAttributes,
    RecordCreateAttributes,
    RecordCreateData,
    RecordCreateRequest,
    RecordResource,
    RecordUpdateAttributes,
    RecordUpdateData,
    RecordUpdateRequest,
    WorkflowStepAttributes,
    WorkflowStepCommentAttributes,
    WorkflowStepCommentResource,
    WorkflowStepResource,
)

__all__ = [
    # Base JSON:API models
    "JSONAPIResponse",
    "Links",
    "Meta",
    "Relationship",
    "RelationshipData",
    "ResourceObject",
    # Enums
    "RecordStatus",
    "StepKind",
    "WorkflowStepStatus",
    # Params
    "BaseListParams",
    "DateRangeFilter",
    "ListRecordsParams",
    "ListRecordGuestsParams",
    "ListRecordAdditionalLocationsParams",
    "ListRecordAttachmentsParams",
    "ListRecordWorkflowStepsParams",
    "ListRecordWorkflowStepCommentsParams",
    "ListRecordCollectionsParams",
    "PageParams",
    # Records
    "RecordAttributes",
    "RecordCreateAttributes",
    "RecordCreateData",
    "RecordCreateRequest",
    "RecordResource",
    "RecordUpdateAttributes",
    "RecordUpdateData",
    "RecordUpdateRequest",
    # Nested resources
    "GuestAttributes",
    "GuestResource",
    "LocationAttributes",
    "LocationResource",
    "AttachmentAttributes",
    "AttachmentResource",
    "WorkflowStepAttributes",
    "WorkflowStepResource",
    "WorkflowStepCommentAttributes",
    "WorkflowStepCommentResource",
    "CollectionAttributes",
    "CollectionResource",
]
